version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis_memory
    environment:
      - REDIS_DB=0
      - REDIS_USER=redis_user
      - REDIS_PASSWORD=redis_password
      - REDIS_MAXMEMORY_MB=10000
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
    command: >
      sh -c "
        redis-server --appendonly yes \
        --requirepass ${REDIS_PASSWORD}
      "
    ports:
      - "6379:6379"
    volumes:
      - data:/data/redis
